#!/bin/bash

set -Eeuo pipefail
IFS=$'\n\t'

# 🔒 SSH Configuration Module (NSA Sec 7.11.1 — Strong Crypto)
MODULE_ID="04-ssh_config"
MODULE_NAME="SSH Configuration"
MODULE_DESC="SSH hardening with strong crypto, source ACL, idle timeout (NSA Sec 7.11.1 + Sec 7.6)"

# Default SSH port (can be overridden by environment variable)
SSH_PORT="${SSH_PORT:-22022}"
# Source-based ACLs (NSA Sec 7.6)
SSH_ALLOWED_SUBNETS="${SSH_ALLOWED_SUBNETS:-192.168.1.0/24,10.0.0.0/8}"
SSHD_CONF_DIR="/etc/ssh/sshd_config.d"

# Source logging library
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../common/logging.sh"

trap 'log error "Failed at line $LINENO"; rollback; module_end "$MODULE_NAME" "failed"; exit 1' ERR
trap 'module_end "$MODULE_NAME" "success"' EXIT

main() {
    module_start "$MODULE_NAME" "$MODULE_DESC"
    
    # ═══════════════════════════════════════════════════════
    step 1 7 "Installing SSH server dependencies"
    explain "Ensuring openssh-server and openssh-client are installed"
    install_dependencies
    
    # ═══════════════════════════════════════════════════════
    step 2 7 "Backing up existing SSH configuration"
    explain "Creating /etc/ssh/sshd_config.bak for rollback capability"
    backup_sshd_config
    
    # ═══════════════════════════════════════════════════════
    step 3 7 "Configuring main sshd_config"
    explain "Setting Port ${SSH_PORT}, key-based auth only, no root login"
    explain "Enforcing Protocol 2, disabling password authentication"
    configure_sshd_main
    
    # ═══════════════════════════════════════════════════════
    step 4 7 "Applying strong cryptographic algorithms (NSA Sec 7.11.1)"
    explain "Ciphers: AES-256-GCM, ChaCha20-Poly1305 (quantum-resistant)"
    explain "Key Exchange: Curve25519, DH-Group-Exchange-SHA256"
    explain "MACs: HMAC-SHA2-512-ETM, HMAC-SHA2-256-ETM"
    configure_strong_crypto
    configure_key_exchange
    configure_macs
    configure_host_keys
    
    # ═══════════════════════════════════════════════════════
    step 5 7 "Configuring source-based access control (NSA Sec 7.6)"
    explain "Restricting SSH access to trusted subnets: ${SSH_ALLOWED_SUBNETS}"
    explain "Denying all other sources via Match Address rules"
    configure_source_acl
    
    # ═══════════════════════════════════════════════════════
    step 6 7 "Setting idle session timeout (NSA Sec 7.11.1)"
    explain "ClientAliveInterval=300s, ClientAliveCountMax=2 → 600s total timeout"
    configure_idle_timeout
    
    # ═══════════════════════════════════════════════════════
    step 7 7 "Validating SSH configuration and restarting service"
    explain "Running sshd -t syntax check, verifying cipher suites, restarting SSH"
    validate
}

install_dependencies() {
    if ! command -v sshd >/dev/null 2>&1; then
        log info "Installing openssh-server and openssh-client"
        apt-get update -qq
        apt-get install -y openssh-server openssh-client
        record_action "openssh-server installed" "✓"
    else
        log info "SSH server already installed (skipping)"
        record_action "openssh-server already present" "✓"
    fi
}

backup_sshd_config() {
    if [ ! -f /etc/ssh/sshd_config.bak ]; then
        cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak
        log info "Backup created: /etc/ssh/sshd_config.bak"
        record_action "sshd_config backed up" "💾"
    else
        log info "Backup already exists (skipping)"
        record_action "sshd_config backup exists" "✓"
    fi
    mkdir -p "${SSHD_CONF_DIR}"
}

configure_sshd_main() {
    log info "Configuring main sshd_config"
    cat > /etc/ssh/sshd_config <<EOF
# Generated by firstb00t module 3 — do not edit manually
# NSA Secure Shell Configuration (CSIS 7.x hardening)

# Port Configuration
Port ${SSH_PORT}
Protocol 2
AddressFamily inet

# Host Key Configuration (NSA Sec 7.11.1)
HostKey /etc/ssh/ssh_host_ed25519_key
HostKey /etc/ssh/ssh_host_rsa_key

# Crypto Configuration (loaded from /etc/ssh/sshd_config.d/)
# See 99-*-hardened.conf files for strong algorithms per NSA Sec 7.11.1

# Authentication (key-based only)
PubkeyAuthentication yes
PasswordAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
UsePAM yes
PermitRootLogin no
MaxAuthTries 3

# Session Management
X11Forwarding no
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
PermitUserEnvironment no
Subsystem sftp /usr/lib/openssh/sftp-server

# Logging (integration with rsyslog Module 10)
SyslogFacility AUTH
LogLevel VERBOSE

# Security Limits
MaxSessions 5
MaxStartups 10:30:100
LoginGraceTime 30

# explicit strong-algorithms in main config to ensure sshd -T shows hardened values
# Strong Symmetric Ciphers
Ciphers aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-gcm@openssh.com

# Strong Key Exchange Algorithms
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256

# Strong Message Authentication Codes
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256

# Strong Host Key Algorithms
HostKeyAlgorithms ssh-ed25519,rsa-sha2-512,rsa-sha2-256

# Idle session timeouts
ClientAliveInterval 300
ClientAliveCountMax 2

# Include hardened crypto configs (also present in /etc/ssh/sshd_config.d/)
Include /etc/ssh/sshd_config.d/99-*.conf
EOF
    record_action "Main sshd_config configured (Port ${SSH_PORT})" "🔒"
    record_action "Key-based auth enforced, passwords disabled" "🔑"
    record_action "Root login disabled (PermitRootLogin no)" "🚫"
    security_impact "SSH port ${SSH_PORT}, key-only auth, strong session limits"
}

configure_strong_crypto() {
    log info "Configuring strong cipher suites (NSA Sec 7.11.1)"
    cat > "${SSHD_CONF_DIR}/99-ciphers-hardened.conf" <<'EOF'
# NSA Secure Shell (CSIS 7.x) — Strong Cipher Configuration
# Reference: NSA Network Infrastructure Security Guide

# Strong Symmetric Ciphers Only (AES-GCM, ChaCha20-Poly1305)
Ciphers aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-gcm@openssh.com

# Strong Key Exchange Algorithms
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256

# Strong Message Authentication Codes
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256

# Strong Host Key Algorithms (Ed25519 preferred, RSA-SHA2-512 fallback)
HostKeyAlgorithms ssh-ed25519,rsa-sha2-512,rsa-sha2-256

# Disable weak algorithms
CASignatureAlgorithms ssh-ed25519,rsa-sha2-512,rsa-sha2-256
EOF
    record_action "Strong ciphers configured (AES-256-GCM, ChaCha20)" "🔐"
    security_impact "Quantum-resistant ciphers, FIPS-compliant algorithms (NSA Sec 7.11.1)"
}

configure_key_exchange() {
    # Explicitly listed in 99-ciphers-hardened.conf for redundancy
    log info "Key exchange algorithms hardened: curve25519, diffie-hellman-group-exchange-sha256"
    record_action "KexAlgorithms: Curve25519, DH-GEX-SHA256" "🔐"
}

configure_macs() {
    # Explicitly listed in 99-ciphers-hardened.conf for redundancy
    log info "MAC algorithms hardened: HMAC-SHA2-512-ETM, HMAC-SHA2-256-ETM"
    record_action "MACs: HMAC-SHA2-512-ETM, HMAC-SHA2-256-ETM" "🔐"
}

configure_source_acl() {
    log info "Configuring source-based access control (NSA Sec 7.6)"
    cat > "${SSHD_CONF_DIR}/99-acl.conf" <<EOF
# NSA Section 7.6 — Source-Based Access Control
# Allow SSH only from management subnets; deny all others

# ✅ Allow from trusted subnets (key-based auth enforced)
Match Address ${SSH_ALLOWED_SUBNETS}
    PubkeyAuthentication yes
    PasswordAuthentication no
    AuthenticationMethods publickey

# ❌ Deny all other sources
Match Address *
    DenyUsers *
EOF
    record_action "Source ACL: Allow ${SSH_ALLOWED_SUBNETS}, Deny others" "🛡️"
    security_impact "Network-layer access control prevents unauthorized SSH attempts (NSA Sec 7.6)"
}

configure_host_keys() {
    # Explicitly listed in 99-ciphers-hardened.conf for redundancy
    log info "Host key algorithms hardened: Ed25519 (preferred), RSA-SHA2-512/256"
    record_action "HostKeyAlgorithms: Ed25519 (preferred), RSA-SHA2" "🔐"
}

configure_idle_timeout() {
    log info "Configuring idle session timeout (NSA Sec 7.11.1)"
    cat > "${SSHD_CONF_DIR}/99-timeouts-hardened.conf" <<'EOF'
# Idle Session Timeout — NSA Sec 7.11.1
# Disconnect clients after 5 minutes (300s) of inactivity
ClientAliveInterval 300
ClientAliveCountMax 2
EOF
    record_action "Idle timeout: 300s interval × 2 attempts = 600s" "⏱️"
    security_impact "Idle sessions terminated after 10 minutes, reducing attack surface"
}

validate() {
    explain "Running 7 validation checks to ensure correct SSH hardening"
    
    # 1️⃣ Check main config syntax
    if ! sshd -t 2>&1; then
        check "SSH config syntax valid (sshd -t)" "false"
        log error "SSH config syntax invalid: $(sshd -t 2>&1 || true)"
        return 1
    fi
    check "SSH config syntax valid (sshd -t)" "true"
    
    # 2️⃣ Verify main config exists and has required settings
    if [ ! -f /etc/ssh/sshd_config ]; then
        check "SSH main config exists" "false"
        log error "Missing /etc/ssh/sshd_config"
        return 1
    fi
    if ! grep -q "Port ${SSH_PORT}" /etc/ssh/sshd_config; then
        check "SSH port configured (Port ${SSH_PORT})" "false"
        log error "Port ${SSH_PORT} not found in sshd_config"
        return 1
    fi
    check "SSH main config present (Port ${SSH_PORT})" "true"
    
    # 3️⃣ Verify strong ciphers configured
    if [ ! -f "${SSHD_CONF_DIR}/99-ciphers-hardened.conf" ]; then
        check "Strong ciphers config exists" "false"
        log error "Missing ${SSHD_CONF_DIR}/99-ciphers-hardened.conf"
        return 1
    fi
    if grep -q "aes256-gcm@openssh.com" "${SSHD_CONF_DIR}/99-ciphers-hardened.conf"; then
        check "Strong ciphers configured (AES-256-GCM)" "true"
    else
        check "Strong ciphers configured (AES-256-GCM)" "false"
        log error "Strong ciphers not configured"
        return 1
    fi
    
    # 4️⃣ Verify idle timeout configured
    if [ ! -f "${SSHD_CONF_DIR}/99-timeouts-hardened.conf" ]; then
        check "Idle timeout config exists" "false"
        log error "Missing ${SSHD_CONF_DIR}/99-timeouts-hardened.conf"
        return 1
    fi
    if grep -q "ClientAliveInterval 300" "${SSHD_CONF_DIR}/99-timeouts-hardened.conf"; then
        check "Idle timeout configured (300s)" "true"
    else
        check "Idle timeout configured (300s)" "false"
        log error "Idle timeout not configured"
        return 1
    fi

    # 5️⃣ Verify source ACL configured (both allow and deny rules)
    if [ ! -f "${SSHD_CONF_DIR}/99-acl.conf" ]; then
        check "Source ACL config exists" "false"
        log error "Missing ${SSHD_CONF_DIR}/99-acl.conf"
        return 1
    fi
    if [ -f "${SSHD_CONF_DIR}/99-acl.conf" ] && \
       grep -q "Match Address" "${SSHD_CONF_DIR}/99-acl.conf" && \
       grep -q "DenyUsers \*" "${SSHD_CONF_DIR}/99-acl.conf"; then
        check "Source-based ACL configured (NSA Sec 7.6)" "true"
    else
        check "Source-based ACL configured (NSA Sec 7.6)" "false"
        log error "Source-based ACL not properly configured"
        return 1
    fi
    
    # 6️⃣ Restart SSH and verify service restarts
    log info "Restarting SSH service to apply configuration"
    if ! systemctl restart ssh 2>&1; then
        check "SSH service restart" "false"
        log error "SSH service restart failed: $(systemctl restart ssh 2>&1 || true)"
        return 1
    fi
    if systemctl is-active --quiet ssh; then
        check "SSH service running and active" "true"
    else
        check "SSH service running and active" "false"
        log error "SSH service not active after restart"
        return 1
    fi
    
    # 7️⃣ Verify service is listening on configured port
    sleep 1  # Give service a moment to stabilize
    if ss -tlnp 2>/dev/null | grep -q ":${SSH_PORT}"; then
        check "SSH listening on port ${SSH_PORT}" "true"
    else
        check "SSH listening on port ${SSH_PORT}" "false"
        log error "SSH not listening on port ${SSH_PORT}"
        log warn "Debug: active ports: $(ss -tlnp 2>/dev/null | grep sshd || true)"
        return 1
    fi
    
    return 0
}

rollback() {
    log warn "Rolling back SSH configuration"
    if [ -f /etc/ssh/sshd_config.bak ]; then
        cp /etc/ssh/sshd_config.bak /etc/ssh/sshd_config
        rm -f "${SSHD_CONF_DIR}/99-"*.conf
        systemctl restart ssh 2>/dev/null || true
        log info "SSH config restored from backup"
    fi
}

main "$@" 