#!/bin/bash
set -Eeuo pipefail
IFS=$'\n\t'

# 🛡️ Fail2ban Module (NSA Sec 6.1, 4.6 — Automated Response + Centralized Logging)
MODULE_ID="07-fail2ban"
REMOTE_SYSLOG="${REMOTE_SYSLOG_SERVER:-remote-syslog-server}"

# Load admin email from profile configuration
if [ -f /home/firstb00t/admin_email ]; then
    ADMIN_EMAIL=$(cat /home/firstb00t/admin_email)
else
    ADMIN_EMAIL="root@localhost"
fi

# Load honeypot configuration
if [ -f /home/firstb00t/honeypot_enabled ]; then
    HONEYPOT_ENABLED=$(cat /home/firstb00t/honeypot_enabled)
else
    HONEYPOT_ENABLED="false"
fi

if [ -f /home/firstb00t/honeypot_whitelist_ip ]; then
    HONEYPOT_WHITELIST_IP=$(cat /home/firstb00t/honeypot_whitelist_ip)
else
    HONEYPOT_WHITELIST_IP=""
fi

# Setup logging
mkdir -p /var/log/firstboot
log() {
    local level=$1; shift
    printf '%s [%s] [%s] %s\n' "$(date -Iseconds)" "$level" "$MODULE_ID" "$*" | tee -a "/var/log/firstboot/${MODULE_ID}.log"
}

trap 'log error "Failed at line $LINENO"; rollback; exit 1' ERR
trap 'log info "Fail2ban configuration completed"' EXIT

main() {
    log info "Starting fail2ban hardening (NSA Sec 6.1, 4.6)"
    
    install_fail2ban
    backup_config
    configure_centralized_logging
    configure_expanded_jails
    restart_services
    validate
}

install_fail2ban() {
    log info "Checking fail2ban package"
    if dpkg -s fail2ban >/dev/null 2>&1; then
        log info "fail2ban already installed"
        return 0
    fi
    
    log info "Installing fail2ban"
    apt-get update && apt-get install -y fail2ban
    log info "fail2ban installed"
}

backup_config() {
    log info "Backing up fail2ban config"
    if [ -f /etc/fail2ban/jail.local ]; then
        if [ ! -f /etc/fail2ban/jail.local.bak ]; then
            cp /etc/fail2ban/jail.local /etc/fail2ban/jail.local.bak
            log info "Backup created: jail.local.bak"
        fi
    fi
    if [ -f /etc/fail2ban/fail2ban.conf ]; then
        if [ ! -f /etc/fail2ban/fail2ban.conf.bak ]; then
            cp /etc/fail2ban/fail2ban.conf /etc/fail2ban/fail2ban.conf.bak
            log info "Backup created: fail2ban.conf.bak"
        fi
    fi
}

configure_centralized_logging() {
    log info "Configuring centralized fail2ban logging (NSA Sec 6.1)"
    
    # Configure fail2ban to use syslog
    if grep -q "^logtarget =" /etc/fail2ban/fail2ban.conf 2>/dev/null; then
        sed -i 's/^logtarget =.*/logtarget = SYSLOG/' /etc/fail2ban/fail2ban.conf
    else
        echo "logtarget = SYSLOG" >> /etc/fail2ban/fail2ban.conf
    fi
    log info "fail2ban logging to syslog configured"
    
    # Configure rsyslog forwarding for fail2ban
    cat > /etc/rsyslog.d/50-fail2ban.conf <<EOF
# Forward fail2ban logs to remote syslog (NSA Sec 6.1)
if \$programname == 'fail2ban' then @@${REMOTE_SYSLOG}:514
& stop
EOF
    log info "rsyslog forwarding configured: ${REMOTE_SYSLOG}:514"
}

configure_expanded_jails() {
    log info "Configuring expanded jail coverage (NSA Sec 4.6)"

    # build ignoreip list from allowlist (if present)
    local ALLOWLIST="127.0.0.1/8"
    if [ -f /home/firstb00t/ssh_allowlist ] && [ -s /home/firstb00t/ssh_allowlist ]; then
        # join lines with spaces
        ALLOWLIST="127.0.0.1/8 $(awk '{print $1}' /home/firstb00t/ssh_allowlist | paste -sd ' ' -)"
    fi

    cat > /etc/fail2ban/jail.local <<EOF
# Fail2ban Jail Configuration — NSA Sec 4.6 (immediate ban on non-key attempts)
# Generated by firstb00t Module 07

[DEFAULT]
# Ban parameters: immediate permanent ban on first attempt without SSH key
bantime = -1         # Permanent ban (no unbanning)
findtime = 1         # 1 second window
maxretry = 1         # Ban on first attempt
destemail = ${ADMIN_EMAIL}
sender = fail2ban@$(hostname -f)
action = %(action_mwl)s

# SSH Protection
[sshd]
enabled = true
port = ${SSH_PORT}
filter = sshd
logpath = /var/log/auth.log
ignoreip = ${ALLOWLIST}
maxretry = 1
findtime = 1
bantime = -1

# SSHD DDoS protection (fast ban)
[sshd-ddos]
enabled = true
port = ${SSH_PORT}
filter = sshd-ddos
logpath = /var/log/auth.log
ignoreip = ${ALLOWLIST}
maxretry = 1
findtime = 1
bantime = -1

# Additional regex coverage for publickey/none failures
# add a lightweight supplemental filter so non-key attempts are counted
EOF

    # add supplemental filter to catch publickey/none failures if present
    cat > /etc/fail2ban/filter.d/sshd-extra.conf <<'EOF'
[Definition]
# additional failregex entries to catch publickey and 'none' auth failures
failregex = Failed publickey for .* from <HOST>
            Failed none for .* from <HOST>
            authentication failure; .* from <HOST>

ignoreregex =
EOF

    log info "Fail2ban jail and supplemental filters written (port=${SSH_PORT}, ignoreip=${ALLOWLIST})"

# HTTP/HTTPS Protection
[apache-auth]
enabled = true
port = http,https
filter = apache-auth
logpath = /var/log/apache2/*error.log
maxretry = 3
findtime = 600
bantime = 3600

[apache-badbots]
enabled = true
port = http,https
filter = apache-badbots
logpath = /var/log/apache2/*access.log
maxretry = 2
findtime = 600
bantime = 86400    # 24 hours for bots

[apache-noscript]
enabled = true
port = http,https
filter = apache-noscript
logpath = /var/log/apache2/*error.log
maxretry = 2
findtime = 600
bantime = 86400

# Nginx Protection
[nginx-http-auth]
enabled = true
port = http,https
filter = nginx-http-auth
logpath = /var/log/nginx/error.log
maxretry = 3
findtime = 600
bantime = 3600

[nginx-limit-req]
enabled = true
port = http,https
filter = nginx-limit-req
logpath = /var/log/nginx/error.log
maxretry = 10
findtime = 600
bantime = 3600

# Mail Server Protection
[postfix-sasl]
enabled = true
port = smtp,submission
filter = postfix-sasl
logpath = /var/log/mail.log
maxretry = 3
findtime = 600
bantime = 3600

[postfix-rbl]
enabled = true
port = smtp,submission
filter = postfix-rbl
logpath = /var/log/mail.log
maxretry = 1
findtime = 600
bantime = 86400

[dovecot]
enabled = true
port = pop3,pop3s,imap,imaps,submission,465,sieve
filter = dovecot
logpath = /var/log/mail.log
maxretry = 3
findtime = 600
bantime = 3600

# FTP Protection
[proftpd]
enabled = true
port = ftp,ftp-data,ftps,ftps-data
filter = proftpd
logpath = /var/log/proftpd/proftpd.log
maxretry = 3
findtime = 600
bantime = 3600

[vsftpd]
enabled = true
port = ftp,ftp-data,ftps,ftps-data
filter = vsftpd
logpath = /var/log/vsftpd.log
maxretry = 3
findtime = 600
bantime = 3600
EOF

    # Add SSH honeypot jail if enabled
    if [ "$HONEYPOT_ENABLED" = "true" ] && [ -n "$HONEYPOT_WHITELIST_IP" ]; then
        log info "Configuring SSH honeypot on port 22 (whitelist: ${HONEYPOT_WHITELIST_IP})"
        cat >> /etc/fail2ban/jail.local <<EOF

# SSH Honeypot (Port 22 Trap) — Permanent Ban
[sshd-honeypot]
enabled = true
port = 22
filter = sshd
logpath = /var/log/auth.log
maxretry = 1           # Instant ban on first attempt
bantime = -1           # Permanent ban (forever)
findtime = 86400       # 24 hour window
ignoreip = 127.0.0.1/8 ${HONEYPOT_WHITELIST_IP}
action = iptables-allports[name=SSH-HONEYPOT]
         %(action_mwl)s
EOF
        log info "SSH honeypot jail configured (permanent ban, whitelist: ${HONEYPOT_WHITELIST_IP})"
    else
        log info "SSH honeypot disabled (port 22 will be blocked by firewall)"
    fi
    
    log info "Expanded jail coverage configured: SSH, HTTP/HTTPS (Apache/Nginx), Mail (Postfix/Dovecot), FTP (ProFTPD/vsftpd), Honeypot (if enabled)"
}

restart_services() {
    log info "Restarting fail2ban and rsyslog services"
    
    systemctl restart fail2ban
    if systemctl is-active --quiet fail2ban; then
        log info "fail2ban restarted successfully"
    else
        log error "fail2ban failed to restart"
        return 1
    fi
    
    systemctl restart rsyslog
    if systemctl is-active --quiet rsyslog; then
        log info "rsyslog restarted successfully"
    else
        log error "rsyslog failed to restart"
        return 1
    fi
}

validate() {
    log info "Validating fail2ban configuration"
    
    # Check fail2ban service status
    if ! systemctl is-active --quiet fail2ban; then
        log error "fail2ban service not active"
        return 1
    fi
    log info "fail2ban service active"
    
    # Check jail.local exists
    if [ ! -f /etc/fail2ban/jail.local ]; then
        log error "jail.local not created"
        return 1
    fi
    log info "jail.local configuration present"
    
    # Check active jails
    local jail_count
    jail_count=$(fail2ban-client status 2>/dev/null | grep -c "Jail list" || echo "0")
    if [ "$jail_count" -eq 0 ]; then
        log warn "No jails detected in fail2ban-client status (may need restart)"
    else
        log info "Jails configured and active"
    fi
    
    # Check centralized logging config
    if grep -q "logtarget = SYSLOG" /etc/fail2ban/fail2ban.conf; then
        log info "Centralized logging configured (syslog)"
    else
        log error "Centralized logging not configured"
        return 1
    fi
    
    # Check rsyslog forwarding config
    if [ -f /etc/rsyslog.d/50-fail2ban.conf ]; then
        log info "rsyslog forwarding configuration present"
    else
        log error "rsyslog forwarding configuration missing"
        return 1
    fi
    
    # Check honeypot configuration if enabled
    if [ "$HONEYPOT_ENABLED" = "true" ]; then
        if grep -q "\[sshd-honeypot\]" /etc/fail2ban/jail.local; then
            log info "SSH honeypot jail configured (port 22 trap)"
        else
            log warn "Honeypot enabled but jail not found in config"
        fi
    fi
    
    return 0
}

rollback() {
    log warn "Rolling back fail2ban configuration"
    if [ -f /etc/fail2ban/jail.local.bak ]; then
        cp /etc/fail2ban/jail.local.bak /etc/fail2ban/jail.local
        log info "jail.local restored from backup"
    fi
    if [ -f /etc/fail2ban/fail2ban.conf.bak ]; then
        cp /etc/fail2ban/fail2ban.conf.bak /etc/fail2ban/fail2ban.conf
        log info "fail2ban.conf restored from backup"
    fi
    rm -f /etc/rsyslog.d/50-fail2ban.conf
    systemctl restart fail2ban rsyslog 2>/dev/null || true
}

main "$@"