#!/bin/bash

set -Eeuo pipefail

# 🔒 SSH Configuration Module
# Default SSH port (can be overridden by environment variable)
SSH_PORT="${SSH_PORT:-22022}"
MODULE_ID="3-ssh_config"

log() {
    local level=$1; shift
    printf '%s [%s] [%s] %s\n' "$(date -Iseconds)" "$level" "$MODULE_ID" "$*" | tee -a "/var/log/firstboot/${MODULE_ID}.log"
}

echo "🔒 Starting SSH configuration with port ${SSH_PORT}..."

    echo "📄 Backing up current SSH configuration..."
    if [ ! -f /etc/ssh/sshd_config.bak ]; then
        cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak
        log info "Backup created at /etc/ssh/sshd_config.bak"
    else
        log info "Backup already exists"
    fi

    echo "⚙️ Configuring SSH security parameters..."
    cat > /etc/ssh/sshd_config <<EOF
# Generated by firstb00t — do not edit manually

# Basic settings
Port ${SSH_PORT}
Protocol 2
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key

# Authentication
PermitRootLogin no
PubkeyAuthentication yes
PasswordAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
UsePAM yes

# Security
X11Forwarding no
PrintMotd no
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server

# Limits
MaxAuthTries 3
MaxSessions 3
LoginGraceTime 30
ClientAliveInterval 300
ClientAliveCountMax 2
EOF

    echo "🔄 Restarting SSH service..."
    if sshd -t; then
        log info "SSH config syntax valid"
    else
        log error "SSH config syntax invalid"
        exit 1
    fi
    
    systemctl restart ssh
    if [ $? -eq 0 ]; then
        echo "🟢 SSH service restarted successfully"
        log info "SSH service restarted"
    else
        echo "🔴 Failed to restart SSH service"
        log error "SSH restart failed"
        exit 1
    fi

    echo "🔍 Verifying SSH configuration..."
    if sshd -t && systemctl is-active --quiet ssh; then
        echo "🟢 SSH configuration valid and service is active"
        log info "SSH configuration verified"
    else
        echo "🔴 SSH verification failed"
        log error "SSH verification failed"
        exit 1
    fi

echo "🟢 SSH configuration completed on port ${SSH_PORT}"
log info "SSH configuration completed" 