#!/bin/bash

set -Eeuo pipefail
IFS=$'\n\t'

# 🔒 SSH Configuration Module (NSA Sec 7.11.1 — Strong Crypto)
# Default SSH port (can be overridden by environment variable)
SSH_PORT="${SSH_PORT:-22}"
# Source-based ACLs (NSA Sec 7.6)
SSH_ALLOWED_SUBNETS="${SSH_ALLOWED_SUBNETS:-192.168.1.0/24,10.0.0.0/8}"
MODULE_ID="3-ssh_config"
SSHD_CONF_DIR="/etc/ssh/sshd_config.d"

# Setup logging
mkdir -p /var/log/firstboot
log() {
    local level=$1; shift
    printf '%s [%s] [%s] %s\n' "$(date -Iseconds)" "$level" "$MODULE_ID" "$*" | tee -a "/var/log/firstboot/${MODULE_ID}.log"
}

trap 'log error "Failed at line $LINENO"; rollback; exit 1' ERR
trap 'log info "SSH config completed"' EXIT

main() {
    log info "Starting SSH hardening (NSA Sec 7.11.1)"
    
    install_dependencies
    backup_sshd_config
    configure_sshd_main
    configure_strong_crypto
    configure_source_acl
    configure_idle_timeout
    configure_key_exchange
    configure_macs
    configure_host_keys
    validate
}

install_dependencies() {
    log info "Checking SSH server package"
    if ! command -v sshd >/dev/null 2>&1; then
        log info "Installing openssh-server"
        apt-get update && apt-get install -y openssh-server openssh-client
    else
        log info "SSH server already installed"
    fi
}

backup_sshd_config() {
    log info "Backing up SSH config"
    if [ ! -f /etc/ssh/sshd_config.bak ]; then
        cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak
        log info "Backup created: /etc/ssh/sshd_config.bak"
    fi
    mkdir -p "${SSHD_CONF_DIR}"
}

configure_sshd_main() {
    log info "Configuring main sshd_config"
    cat > /etc/ssh/sshd_config <<'EOF'
# Generated by firstb00t module 3 — do not edit manually
# NSA Secure Shell Configuration (CSIS 7.x hardening)

# Port Configuration
Port ${SSH_PORT}
Protocol 2
AddressFamily inet

# Host Key Configuration (NSA Sec 7.11.1)
HostKey /etc/ssh/ssh_host_ed25519_key
HostKey /etc/ssh/ssh_host_rsa_key

# Crypto Configuration (loaded from /etc/ssh/sshd_config.d/)
# See 99-*-hardened.conf files for strong algorithms per NSA Sec 7.11.1

# Authentication (key-based only)
PubkeyAuthentication yes
PasswordAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
UsePAM yes
PermitRootLogin no
MaxAuthTries 3

# Session Management
X11Forwarding no
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
PermitUserEnvironment no
Subsystem sftp /usr/lib/openssh/sftp-server

# Logging (integration with rsyslog Module 10)
SyslogFacility AUTH
LogLevel VERBOSE

# Security Limits
MaxSessions 5
MaxStartups 10:30:100
LoginGraceTime 30

# Include hardened crypto configs
Include /etc/ssh/sshd_config.d/99-*.conf
EOF
    log info "Main sshd_config configured"
}

configure_strong_crypto() {
    log info "Configuring strong cipher suites (NSA Sec 7.11.1)"
    cat > "${SSHD_CONF_DIR}/99-ciphers-hardened.conf" <<'EOF'
# NSA Secure Shell (CSIS 7.x) — Strong Cipher Configuration
# Reference: NSA Network Infrastructure Security Guide

# Strong Symmetric Ciphers Only (AES-GCM, ChaCha20-Poly1305)
Ciphers aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-gcm@openssh.com

# Strong Key Exchange Algorithms
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256

# Strong Message Authentication Codes
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256

# Strong Host Key Algorithms (Ed25519 preferred, RSA-SHA2-512 fallback)
HostKeyAlgorithms ssh-ed25519,rsa-sha2-512,rsa-sha2-256

# Disable weak algorithms
CASignatureAlgorithms ssh-ed25519,rsa-sha2-512,rsa-sha2-256
EOF
    log info "Cipher suite configured"
}

configure_key_exchange() {
    log info "Verifying key exchange algorithms (NSA Sec 7.11.1)"
    # Explicitly listed in 99-ciphers-hardened.conf for redundancy
    log info "Key exchange algorithms hardened: curve25519, diffie-hellman-group-exchange-sha256"
}

configure_macs() {
    log info "Verifying MAC algorithms (NSA Sec 7.11.1)"
    # Explicitly listed in 99-ciphers-hardened.conf for redundancy
    log info "MAC algorithms hardened: HMAC-SHA2-512-ETM, HMAC-SHA2-256-ETM"
}

configure_source_acl() {
    log info "Configuring source-based access control (NSA Sec 7.6)"
    cat > "${SSHD_CONF_DIR}/99-acl.conf" <<EOF
# NSA Section 7.6 — Source-Based Access Control
# Allow SSH only from management subnets
Match Address ${SSH_ALLOWED_SUBNETS}
    PasswordAuthentication no
    PubkeyAuthentication yes

# Deny all other sources
Match Address *,!${SSH_ALLOWED_SUBNETS}
    DenyUsers *
EOF
    log info "Source ACL configured for subnets: ${SSH_ALLOWED_SUBNETS}"
}

configure_host_keys() {
    log info "Verifying host key algorithms (NSA Sec 7.11.1)"
    # Explicitly listed in 99-ciphers-hardened.conf for redundancy
    log info "Host key algorithms hardened: Ed25519 (preferred), RSA-SHA2-512/256"
}

configure_idle_timeout() {
    log info "Configuring idle session timeout (NSA Sec 7.11.1)"
    cat > "${SSHD_CONF_DIR}/99-timeouts-hardened.conf" <<'EOF'
# Idle Session Timeout — NSA Sec 7.11.1
# Disconnect clients after 5 minutes (300s) of inactivity
ClientAliveInterval 300
ClientAliveCountMax 2
EOF
    log info "Idle timeout configured: 300s interval, 2 keep-alive attempts = 600s total disconnect"
}

validate() {
    log info "Validating SSH configuration"
    
    # Check syntax
    if ! sshd -t; then
        log error "SSH config syntax invalid"
        return 1
    fi
    log info "SSH config syntax valid"
    
    # Verify strong ciphers configured
    if grep -q "aes256-gcm@openssh.com" "${SSHD_CONF_DIR}/99-ciphers-hardened.conf"; then
        log info "Strong ciphers (AES-256-GCM) configured"
    else
        log error "Strong ciphers not configured"
        return 1
    fi
    
    # Verify idle timeout configured
    if grep -q "ClientAliveInterval 300" "${SSHD_CONF_DIR}/99-timeouts-hardened.conf"; then
        log info "Idle timeout configured (300s)"
    else
        log error "Idle timeout not configured"
        return 1
    fi

    # Verify source ACL configured
    if grep -q "Match Address" "${SSHD_CONF_DIR}/99-acl.conf"; then
        log info "Source-based ACL configured (NSA Sec 7.6)"
    else
        log error "Source-based ACL not configured"
        return 1
    fi
    
    # Restart SSH and verify
    systemctl restart ssh
    if systemctl is-active --quiet ssh; then
        log info "SSH service restarted successfully"
    else
        log error "SSH service failed to restart"
        return 1
    fi
    
    # Verify service is listening
    if ss -tlnp | grep -q "sshd"; then
        log info "SSH service is listening on configured port"
    else
        log error "SSH service not listening"
        return 1
    fi
    
    return 0
}

rollback() {
    log warn "Rolling back SSH configuration"
    if [ -f /etc/ssh/sshd_config.bak ]; then
        cp /etc/ssh/sshd_config.bak /etc/ssh/sshd_config
        rm -f "${SSHD_CONF_DIR}/99-"*.conf
        systemctl restart ssh 2>/dev/null || true
        log info "SSH config restored from backup"
    fi
}

main "$@" 