#!/bin/bash

set -Eeuo pipefail

# 🌈 color definitions
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # no color

# 📋 module information
MODULE_ID="3-ssh_hardening"
SSH_PORT="${SSH_PORT:-22022}"

log() {
    local level=$1; shift
    printf '%s [%s] [%s] %s\n' "$(date -Iseconds)" "$level" "$MODULE_ID" "$*" | tee -a "/var/log/firstboot/${MODULE_ID}.log"
}

# 🚨 Error handling
on_error() {
    local line=${1:-unknown}
    log error "Failed at line ${line}"
    [ -f /etc/ssh/sshd_config.bak ] && cp /etc/ssh/sshd_config.bak /etc/ssh/sshd_config
    systemctl restart sshd || true
    return 1
}

trap 'on_error $LINENO' ERR

# 🧹 Cleanup function
cleanup() {
    log info "Cleanup completed"
}

# 🔄 Check dependencies
check_dependencies() {
    log info "Checking dependencies..."
    command -v sshd >/dev/null || { log error "sshd not found"; exit 1; }
    command -v systemctl >/dev/null || { log error "systemctl not found"; exit 1; }
}

# 📊 Progress tracking
update_progress() {
    log info "Step $1 of $2"
}

# 🔒 Configure SSH
configure_ssh() {
    log info "Configuring SSH hardening..."
    
    # Backup original config
    if [ ! -f /etc/ssh/sshd_config.bak ]; then
        cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak
        log info "Backup created"
    fi
    
    # Create hardened config (references port from environment)
    cat > /etc/ssh/sshd_config << EOF
# Hardened SSH configuration generated by firstb00t
# Port configured to: ${SSH_PORT}

Port ${SSH_PORT}

# Authentication
PermitRootLogin no
PubkeyAuthentication yes
PasswordAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
UsePAM yes

# Security
Protocol 2
X11Forwarding no
AllowAgentForwarding no
AllowTcpForwarding no
PermitUserEnvironment no
ClientAliveInterval 300
ClientAliveCountMax 2
MaxAuthTries 3
MaxSessions 2
LoginGraceTime 60

# Logging
SyslogFacility AUTH
LogLevel VERBOSE

# Other
Banner /etc/issue.net
EOF
    
    chmod 600 /etc/ssh/sshd_config
    log info "SSH configuration completed"
    
    log info "SSH configuration written"
}

# 🔄 Restart service
restart_service() {
    log info "Restarting SSH service..."
    
    # Test config syntax
    sshd -t || { log error "Invalid SSH config syntax"; exit 1; }
    
    # Restart service
    systemctl restart sshd || { log error "Failed to restart SSH"; exit 1; }
    
    # Verify service status
    systemctl is-active --quiet sshd || { log error "SSH service not active"; exit 1; }
    
    log info "SSH service restarted successfully"
}

# 🎯 Main function
main() {
    log info "SSH hardening module starting with port ${SSH_PORT}"

    check_dependencies
    update_progress 1 3
    configure_ssh
    log info "Step 1 completed"

    update_progress 2 3
    restart_service
    log info "Step 2 completed"

    update_progress 3 3
    # Final verification
    sshd -t || { log error "SSH config invalid"; exit 1; }
    systemctl is-active --quiet sshd || { log error "SSH service not active"; exit 1; }
    log info "Step 3 completed - verification passed"

    log info "SSH hardening module completed successfully"
}

main "$@" 