#!/bin/bash
set -Eeuo pipefail
IFS=$'\n\t'

# 🛡️ Fail2ban Module (NSA Sec 6.1, 4.6 — Automated Response + Centralized Logging)
MODULE_ID="6-fail2ban"
REMOTE_SYSLOG="${REMOTE_SYSLOG_SERVER:-remote-syslog-server}"

# Setup logging
mkdir -p /var/log/firstboot
log() {
    local level=$1; shift
    printf '%s [%s] [%s] %s\n' "$(date -Iseconds)" "$level" "$MODULE_ID" "$*" | tee -a "/var/log/firstboot/${MODULE_ID}.log"
}

trap 'log error "Failed at line $LINENO"; rollback; exit 1' ERR
trap 'log info "Fail2ban configuration completed"' EXIT

main() {
    log info "Starting fail2ban hardening (NSA Sec 6.1, 4.6)"
    
    install_fail2ban
    backup_config
    configure_centralized_logging
    configure_expanded_jails
    restart_services
    validate
}

install_fail2ban() {
    log info "Checking fail2ban package"
    if dpkg -s fail2ban >/dev/null 2>&1; then
        log info "fail2ban already installed"
        return 0
    fi
    
    log info "Installing fail2ban"
    apt-get update && apt-get install -y fail2ban
    log info "fail2ban installed"
}

backup_config() {
    log info "Backing up fail2ban config"
    if [ -f /etc/fail2ban/jail.local ]; then
        if [ ! -f /etc/fail2ban/jail.local.bak ]; then
            cp /etc/fail2ban/jail.local /etc/fail2ban/jail.local.bak
            log info "Backup created: jail.local.bak"
        fi
    fi
    if [ -f /etc/fail2ban/fail2ban.conf ]; then
        if [ ! -f /etc/fail2ban/fail2ban.conf.bak ]; then
            cp /etc/fail2ban/fail2ban.conf /etc/fail2ban/fail2ban.conf.bak
            log info "Backup created: fail2ban.conf.bak"
        fi
    fi
}

configure_centralized_logging() {
    log info "Configuring centralized fail2ban logging (NSA Sec 6.1)"
    
    # Configure fail2ban to use syslog
    if grep -q "^logtarget =" /etc/fail2ban/fail2ban.conf 2>/dev/null; then
        sed -i 's/^logtarget =.*/logtarget = SYSLOG/' /etc/fail2ban/fail2ban.conf
    else
        echo "logtarget = SYSLOG" >> /etc/fail2ban/fail2ban.conf
    fi
    log info "fail2ban logging to syslog configured"
    
    # Configure rsyslog forwarding for fail2ban
    cat > /etc/rsyslog.d/50-fail2ban.conf <<EOF
# Forward fail2ban logs to remote syslog (NSA Sec 6.1)
if \$programname == 'fail2ban' then @@${REMOTE_SYSLOG}:514
& stop
EOF
    log info "rsyslog forwarding configured: ${REMOTE_SYSLOG}:514"
}

configure_expanded_jails() {
    log info "Configuring expanded jail coverage (NSA Sec 4.6)"
    
    cat > /etc/fail2ban/jail.local <<'EOF'
# Fail2ban Jail Configuration — NSA Sec 4.6 (≤3 attempts)
# Generated by firstb00t Module 6

[DEFAULT]
# Ban parameters per NSA Sec 4.6
bantime = 3600       # 1 hour ban
findtime = 600       # 10 minute window
maxretry = 3         # NSA Sec 4.6 limit (≤3 attempts)
destemail = root@localhost
sender = fail2ban@localhost
action = %(action_mwl)s

# SSH Protection
[sshd]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
findtime = 600
bantime = 3600

[sshd-ddos]
enabled = true
port = ssh
filter = sshd-ddos
logpath = /var/log/auth.log
maxretry = 3
findtime = 600
bantime = 3600

# HTTP/HTTPS Protection
[apache-auth]
enabled = true
port = http,https
filter = apache-auth
logpath = /var/log/apache2/*error.log
maxretry = 3
findtime = 600
bantime = 3600

[apache-badbots]
enabled = true
port = http,https
filter = apache-badbots
logpath = /var/log/apache2/*access.log
maxretry = 2
findtime = 600
bantime = 86400    # 24 hours for bots

[apache-noscript]
enabled = true
port = http,https
filter = apache-noscript
logpath = /var/log/apache2/*error.log
maxretry = 2
findtime = 600
bantime = 86400

# Nginx Protection
[nginx-http-auth]
enabled = true
port = http,https
filter = nginx-http-auth
logpath = /var/log/nginx/error.log
maxretry = 3
findtime = 600
bantime = 3600

[nginx-limit-req]
enabled = true
port = http,https
filter = nginx-limit-req
logpath = /var/log/nginx/error.log
maxretry = 10
findtime = 600
bantime = 3600

# Mail Server Protection
[postfix-sasl]
enabled = true
port = smtp,submission
filter = postfix-sasl
logpath = /var/log/mail.log
maxretry = 3
findtime = 600
bantime = 3600

[postfix-rbl]
enabled = true
port = smtp,submission
filter = postfix-rbl
logpath = /var/log/mail.log
maxretry = 1
findtime = 600
bantime = 86400

[dovecot]
enabled = true
port = pop3,pop3s,imap,imaps,submission,465,sieve
filter = dovecot
logpath = /var/log/mail.log
maxretry = 3
findtime = 600
bantime = 3600

# FTP Protection
[proftpd]
enabled = true
port = ftp,ftp-data,ftps,ftps-data
filter = proftpd
logpath = /var/log/proftpd/proftpd.log
maxretry = 3
findtime = 600
bantime = 3600

[vsftpd]
enabled = true
port = ftp,ftp-data,ftps,ftps-data
filter = vsftpd
logpath = /var/log/vsftpd.log
maxretry = 3
findtime = 600
bantime = 3600
EOF
    log info "Expanded jail coverage configured: SSH, HTTP/HTTPS (Apache/Nginx), Mail (Postfix/Dovecot), FTP (ProFTPD/vsftpd)"
}

restart_services() {
    log info "Restarting fail2ban and rsyslog services"
    
    systemctl restart fail2ban
    if systemctl is-active --quiet fail2ban; then
        log info "fail2ban restarted successfully"
    else
        log error "fail2ban failed to restart"
        return 1
    fi
    
    systemctl restart rsyslog
    if systemctl is-active --quiet rsyslog; then
        log info "rsyslog restarted successfully"
    else
        log error "rsyslog failed to restart"
        return 1
    fi
}

validate() {
    log info "Validating fail2ban configuration"
    
    # Check fail2ban service status
    if ! systemctl is-active --quiet fail2ban; then
        log error "fail2ban service not active"
        return 1
    fi
    log info "fail2ban service active"
    
    # Check jail.local exists
    if [ ! -f /etc/fail2ban/jail.local ]; then
        log error "jail.local not created"
        return 1
    fi
    log info "jail.local configuration present"
    
    # Check active jails
    local jail_count
    jail_count=$(fail2ban-client status 2>/dev/null | grep -c "Jail list" || echo "0")
    if [ "$jail_count" -eq 0 ]; then
        log warn "No jails detected in fail2ban-client status (may need restart)"
    else
        log info "Jails configured and active"
    fi
    
    # Check centralized logging config
    if grep -q "logtarget = SYSLOG" /etc/fail2ban/fail2ban.conf; then
        log info "Centralized logging configured (syslog)"
    else
        log error "Centralized logging not configured"
        return 1
    fi
    
    # Check rsyslog forwarding config
    if [ -f /etc/rsyslog.d/50-fail2ban.conf ]; then
        log info "rsyslog forwarding configuration present"
    else
        log error "rsyslog forwarding configuration missing"
        return 1
    fi
    
    return 0
}

rollback() {
    log warn "Rolling back fail2ban configuration"
    if [ -f /etc/fail2ban/jail.local.bak ]; then
        cp /etc/fail2ban/jail.local.bak /etc/fail2ban/jail.local
        log info "jail.local restored from backup"
    fi
    if [ -f /etc/fail2ban/fail2ban.conf.bak ]; then
        cp /etc/fail2ban/fail2ban.conf.bak /etc/fail2ban/fail2ban.conf
        log info "fail2ban.conf restored from backup"
    fi
    rm -f /etc/rsyslog.d/50-fail2ban.conf
    systemctl restart fail2ban rsyslog 2>/dev/null || true
}

main "$@"
port = pop3,pop3s,imap,imaps
filter = dovecot
logpath = /var/log/mail.log
maxretry = 3
findtime = 600
bantime = 3600
EOF
    
    # set permissions
    chmod 644 /etc/fail2ban/jail.local || handle_error "échec de la définition des permissions" "définition des permissions"
    
    log_action "info : configuration de fail2ban effectuée"
}

# 🔄 restart service
restart_service() {
    echo -e "${BLUE}🔄 redémarrage du service fail2ban...${NC}"
    
    # restart service
    systemctl restart fail2ban || handle_error "échec du redémarrage du service" "redémarrage du service"
    
    # verify service status
    if ! systemctl is-active --quiet fail2ban; then
        handle_error "service fail2ban non actif" "vérification du service"
    fi
    
    log_action "info : service fail2ban redémarré"
}

# 🎯 main function
main() {
    echo -e "${CYAN}╔════════════════════════════════════════════════════════════
║ 🚀 installation du module $MODULE_NAME...                    
╚════════════════════════════════════════════════════════════${NC}"
profile enablement
    if [ ! -f "/etc/firstboot/modules/${MODULE_NAME}.enabled" ]; then
        log_action "info: module disabled for this profile; skipping"
        echo -e "${YELLOW}⏭️  module non activé pour ce profil${NC}"
        exit 0
    fi

    # check 
    # check dependencies
    check_dependencies

    # step 1: install fail2ban
    update_progress 1 4
    echo -e "${BLUE}📦 étape 1 : installation...${NC}"
    install_fail2ban
    log_action "info : étape 1 terminée"

    # step 2: configure fail2ban
    update_progress 2 4
    echo -e "${BLUE}📦 étape 2 : configuration...${NC}"
    configure_fail2ban
    log_action "info : étape 2 terminée"

    # step 3: restart service
    update_progress 3 4
    echo -e "${BLUE}📦 étape 3 : redémarrage du service...${NC}"
    restart_service
    log_action "info : étape 3 terminée"

    # step 4: verify
    update_progress 4 4
    echo -e "${BLUE}📦 étape 4 : vérification...${NC}"
    
    # verify service
    if ! systemctl is-active --quiet fail2ban; then
        handle_error "service fail2ban non actif" "vérification"
    fi
    
    # verify jails
    if ! fail2ban-client status | grep -q "Status: active"; then
        handle_error "fail2ban non actif" "vérification"
    fi
    
    log_action "info : étape 4 terminée"

    echo -e "${GREEN}🎉 module $MODULE_NAME installé avec succès${NC}"
    log_action "succès : installation du module $MODULE_NAME terminée"
}

# 🎯 run main function
main 